### ISSUE TITLE
7.11.2 is missing from maven central

### ISSUE THREAD

**Issue by neowu** [codelibs/elasticsearch-module#12]
module lib stoped to update since 7.10.2, any update on 7.11.2? 
e.g. 
https://mvnrepository.com/artifact/org.codelibs.elasticsearch.module/lang-painless

**Comment by grimsa** [comment]
Noticed the same issue after upgrading to 7.12.1 ElasticSearch

**Comment by marevol** [comment]
See [README.md](https://github.com/codelibs/elasticsearch-module#version)

**Comment by dantran** [comment]
is there a reason not seeing 7.10.2 + showing up at maven central  instead of only   at https://maven.codelibs.org/org/codelibs/elasticsearch/module

**Comment by marevol** [comment]
We use our maven repository after the license change.

**Comment by dantran** [comment]
strange, i still see elasicsearch showing up at  https://repo1.maven.org/maven2.  but not codelib, the license change prevents locdelib from posting at maven central does not make sense to me.   Having codelib in a another maven repo very inconvenient for us

The reason could be  ElasticSearch owns those jars and codelib has no right to push them to maven central on ES' behalf?

**Comment by marevol** [comment]
Basically, we use this library for our projects. elasticsearch is not OSS now, so we do not put it to our maven central. Our build script is open in this GitHub repository, and you can put it to your maven central if you need it.

**Comment by dantran** [comment]
I am seeing the latest commit switches license to SSPL, however the uploaded ones at https://maven.codelibs.org/org/codelibs/elasticsearch/module are still at ApacheV2.  Are they valid?

**Comment by marevol** [comment]
They are SSPL.

**Comment by dantran** [comment]
@marevol  according to 7.16.2  https://maven.codelibs.org/org/codelibs/elasticsearch/module/analysis-common/7.16.2/analysis-common-7.16.2.pom  it shows ApacheV2

Could you update them to SSPL?

**Comment by mark-vieira** [comment]
Thanks for pointing that out @dantran. @marevol all these artifacts starting with version 7.11 and later are no longer Apache 2.0. Rehosting them under an Apache 2.0 license is in violation of both SSPL and Elastic v2 licenses. You'll need to either remove these artifacts or update the POMs to reflect the actual license. Here's an example of what would be permissable:

```xml
  <licenses>
    <license>
      <name>Elastic License 2.0</name>
      <url>https://raw.githubusercontent.com/elastic/elasticsearch/master/licenses/ELASTIC-LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
    <license>
      <name>Server Side Public License, v 1</name>
      <url>https://www.mongodb.com/licensing/server-side-public-license</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <name>Elastic</name>
      <url>https://www.elastic.co</url>
    </developer>
  </developers>
```

**Comment by mark-vieira** [comment]
To add to this, the same applies the artifacts under https://maven.codelibs.org/org/codelibs/elasticsearch/lib/. These are also no longer Apache 2.0, but dual licensed SSPL and Elastic v2.

**Comment by mark-vieira** [comment]
@marevol any update on this? As stated, redistributing Elasticsearch artifacts for versions 7.11 and later with incorrect license attribution is in violation of both supported licenses. We don't want to risk confusion regarding license terms here with folks unknowingly grabbing these artifacts from your public repository.

**Comment by marevol** [comment]
done

**Comment by mark-vieira** [comment]
Thanks!
