### ISSUE TITLE
lang-painless missing dependency on scripting-painless-spi?

### ISSUE THREAD

**Issue by grimsa** [codelibs/elasticsearch-module#13]
After upgrading Elasticsearch from 7.12.1 to 7.15.2 we ran into a compilation issue - `org.elasticsearch.painless.spi.*` classes were not being found in `org.elasticsearch.painless.PainlessPlugin`.

Adding an additional `runtimeOnly "org.codelibs.elasticsearch.module:scripting-painless-spi:${elasticsearchVersion}"` dependency seems to resolve the issue.

Shouldn't `org.codelibs.elasticsearch.module:lang-painless` library POM file have a dependency on `scripting-painless-spi`?
POM file: https://maven.codelibs.org/org/codelibs/elasticsearch/module/lang-painless/7.15.2/lang-painless-7.15.2.pom

**Comment by marevol** [comment]
It will be added in the next release.
