### ISSUE TITLE
x-pack required

### ISSUE THREAD

**Issue by otrosien** [codelibs/elasticsearch-module#3]
Newer versions of Elasticsearch come with x-pack bundled, and trying to join a cluster without x-pack leads to this:

```
RemoteTransportException[[dtczN_K][10.2.38.131:9300][internal:discovery/zen/join/validate]]; nested: IllegalArgumentException[Unknown NamedWriteable [org.elasticsearch.cluster.metadata.MetaData$Custom][licenses]];
```

Please add x-pack to the published artifacts. If you want I can help out with a PR.

**Comment by marevol** [comment]
I do not think that X-Pack is OSS...

**Comment by otrosien** [comment]
What alternatives do you see? I don't think we can uninstall x-pack, which means currently it's impossible to join a 6.3.0+ cluster.

**Comment by otrosien** [comment]
AFAICS we would need at least the x-pack-client to be able to join the cluster:

https://github.com/elastic/elasticsearch/blob/079d130d8c4827426ee15e7d7964b1c993a6c491/docs/reference/setup/setup-xclient.asciidoc

I will check if that's OSS.

**Comment by otrosien** [comment]
After some digging I think I found it, and what I found is basically bad news. x-pack-transport depends on x-pack-core, which is proprietary.

https://github.com/elastic/elasticsearch/blob/82d10b484a20514e70f6d773544ffea62e57f711/x-pack/transport-client/build.gradle#L9

Any other solution to spin up an Elasticsearch cluster completely without x-pack?

**Comment by marevol** [comment]
I'm not sure about your problem...
[ElasticsearchClusterRunnerTest](https://github.com/codelibs/elasticsearch-cluster-runner/blob/master/src/test/java/org/codelibs/elasticsearch/runner/ElasticsearchClusterRunnerTest.java) works without X-Pack.

**Comment by otrosien** [comment]
Sorry for the confusion. I overlooked the pure OSS distribution link. https://www.elastic.co/downloads/elasticsearch-oss

Closing this as not an issue.
